server:
  port: 9085
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/brian-alan/microservices
          search-paths: config-data
  application:
    name: config-service